name: Node CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --include=dev
    - run: npm run lint
    - run: npm run build --  --no-color
    - run: npm run test:cover
    - name: Code Coverage
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/cobertura-coverage.xml
        badge: true
        fail_below_min: false #TODO: set a threshold
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md        
